#!/bin/bash
#############################################################################
# TerminatorZ v3.0 - Reporter Module
# Parses structured findings (target/poc/proof) into HTML and Markdown.
#############################################################################

generate_report() {
    local domain=$1
    tz_info "Generating reports..."
    generate_markdown_report "$domain"
    generate_html_report "$domain"
    tz_ok "Reports generated:"
    echo "    - $TZ_CURRENT_RESULT_PATH/report.md"
    echo "    - $TZ_CURRENT_RESULT_PATH/report.html"
}

# Parse findings file into structured blocks by severity.
# Findings file format (per finding):
#   [SEVERITY] Display Name
#     target: <url>
#     poc:    <url>
#     proof:  <text>
#
#   (blank line between findings)
# Emits a JSON-ish array to stdout: one finding per line
#   SEV|NAME|TARGET|POC|PROOF
_parse_findings() {
    local findings_file=$1
    [ ! -f "$findings_file" ] && return 0

    awk '
    BEGIN { sev=""; name=""; tgt=""; poc=""; prf="" }
    /^\[(CRITICAL|HIGH|MEDIUM|LOW)\]/ {
        if (sev != "") {
            print sev "|" name "|" tgt "|" poc "|" prf
        }
        line = $0
        # Portable extraction: strip leading "[" then split on "] "
        sub(/^\[/, "", line)
        idx = index(line, "] ")
        if (idx > 0) {
            sev  = substr(line, 1, idx - 1)
            name = substr(line, idx + 2)
        } else {
            sev  = ""
            name = line
        }
        tgt = ""; poc = ""; prf = ""
        next
    }
    /^[[:space:]]*target:/ { sub(/^[[:space:]]*target:[[:space:]]*/,"",$0); tgt=$0; next }
    /^[[:space:]]*poc:/    { sub(/^[[:space:]]*poc:[[:space:]]*/,"",$0);    poc=$0; next }
    /^[[:space:]]*proof:/  { sub(/^[[:space:]]*proof:[[:space:]]*/,"",$0);  prf=$0; next }
    END {
        if (sev != "") { print sev "|" name "|" tgt "|" poc "|" prf }
    }
    ' "$findings_file"
}

#############################################################################
# Markdown report
#############################################################################
generate_markdown_report() {
    local domain=$1
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    local findings_file="$TZ_CURRENT_RESULT_PATH/$domain.txt"
    local report_file="$TZ_CURRENT_RESULT_PATH/report.md"

    recompute_stats "$domain"

    {
        echo "# TerminatorZ v3.0 Security Report"
        echo
        echo "**Target:** $domain"
        echo "**Date:** $timestamp"
        echo "**Run:** $(basename "$TZ_CURRENT_RESULT_PATH")"
        echo "**Author:** Chris 'SaintDruG' Abou-Chabké"
        echo "**Organization:** Black Hat Ethical Hacking"
        echo "**Website:** https://www.blackhatethicalhacking.com"
        echo
        echo "---"
        echo
        echo "## Executive Summary"
        echo
        echo "| Metric | Count |"
        echo "|---|---|"
        echo "| Total URLs scanned | $TOTAL_URLS |"
        echo "| Critical | $VULN_CRITICAL |"
        echo "| High | $VULN_HIGH |"
        echo "| Medium | $VULN_MEDIUM |"
        echo "| Low | $VULN_LOW |"
        echo
        echo "---"
        echo
        echo "## Findings"
        echo

        local sev
        for sev in CRITICAL HIGH MEDIUM LOW; do
            echo "### $sev"
            echo
            local any=0
            local line
            while IFS='|' read -r s name tgt poc prf; do
                [ "$s" != "$sev" ] && continue
                any=1
                echo "**$name**"
                echo
                echo "- Target: \`$tgt\`"
                echo "- Proof-of-Concept: \`$poc\`"
                [ -n "$prf" ] && echo "- Proof: $prf"
                echo
            done < <(_parse_findings "$findings_file")
            [ $any -eq 0 ] && { echo "_None._"; echo; }
        done

        echo "---"
        echo
        echo "## Notes"
        echo
        echo "This report was generated for authorised security testing only."
        echo "Findings are passive-scan indicators and must be manually validated before reporting."
        echo
        echo "_Generated by TerminatorZ v3.0 — https://www.blackhatethicalhacking.com_"
        echo "_Author: Chris 'SaintDruG' Abou-Chabké_"
    } > "$report_file"
}

#############################################################################
# HTML report
#############################################################################
generate_html_report() {
    local domain=$1
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    local findings_file="$TZ_CURRENT_RESULT_PATH/$domain.txt"
    local report_file="$TZ_CURRENT_RESULT_PATH/report.html"
    local run_label
    run_label=$(basename "$TZ_CURRENT_RESULT_PATH")

    recompute_stats "$domain"

    # Build per-severity HTML blocks
    local critical_html high_html medium_html low_html
    critical_html=$(_findings_html_blocks "$findings_file" "CRITICAL")
    high_html=$(_findings_html_blocks    "$findings_file" "HIGH")
    medium_html=$(_findings_html_blocks  "$findings_file" "MEDIUM")
    low_html=$(_findings_html_blocks     "$findings_file" "LOW")

    cat > "$report_file" <<HTMLEOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>TerminatorZ Security Report — $domain</title>
<style>
  body {
    background: #05050a;
    color: #e0e0e0;
    font-family: 'Courier New', Consolas, monospace;
    padding: 30px;
    line-height: 1.6;
    margin: 0;
  }
  .header {
    border: 2px solid #ff00ff;
    box-shadow: 0 0 25px #ff00ff55;
    padding: 28px;
    margin-bottom: 30px;
    text-align: center;
    border-radius: 6px;
  }
  h1 {
    color: #ff00ff;
    text-shadow: 0 0 12px #ff00ff;
    margin: 0 0 12px 0;
    font-size: 28px;
    letter-spacing: 2px;
  }
  .subtitle {
    color: #00ffff;
    text-shadow: 0 0 8px #00ffff88;
    font-size: 14px;
    margin-bottom: 16px;
  }
  h2 {
    color: #00ffff;
    text-shadow: 0 0 6px #00ffff88;
    border-bottom: 1px solid #00ffff;
    padding-bottom: 8px;
    margin-top: 40px;
  }
  h3 { margin-top: 30px; font-size: 18px; }
  h3.critical { color: #ff0044; text-shadow: 0 0 6px #ff004488; }
  h3.high     { color: #ff8800; text-shadow: 0 0 6px #ff880088; }
  h3.medium   { color: #ffee00; text-shadow: 0 0 6px #ffee0088; }
  h3.low      { color: #00ffff; text-shadow: 0 0 6px #00ffff88; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  th {
    background: #1a0033;
    color: #ff00ff;
    padding: 12px;
    text-align: left;
    border: 1px solid #ff00ff66;
  }
  td {
    padding: 12px;
    border: 1px solid #333355;
  }
  tr:nth-child(even) td { background: #0a0a14; }
  .count-critical { color: #ff0044; font-weight: bold; }
  .count-high     { color: #ff8800; font-weight: bold; }
  .count-medium   { color: #ffee00; font-weight: bold; }
  .count-low      { color: #00ffff; font-weight: bold; }
  .finding {
    background: #0a0a14;
    padding: 16px 18px;
    margin: 14px 0;
    border-left: 4px solid;
    border-radius: 3px;
    font-size: 13px;
  }
  .finding.critical { border-left-color: #ff0044; }
  .finding.high     { border-left-color: #ff8800; }
  .finding.medium   { border-left-color: #ffee00; }
  .finding.low      { border-left-color: #00ffff; }
  .finding-name {
    font-weight: bold;
    color: #ffffff;
    font-size: 14px;
    margin-bottom: 8px;
  }
  .finding-row { margin: 4px 0; }
  .label { color: #00ffff; display: inline-block; min-width: 72px; }
  .value {
    color: #e0e0e0;
    word-break: break-all;
    background: #000;
    padding: 2px 6px;
    border-radius: 2px;
    font-family: 'Courier New', monospace;
  }
  .value.proof { background: transparent; color: #aaa; font-style: italic; }
  .none { color: #666; font-style: italic; padding: 12px; }
  .footer {
    margin-top: 60px;
    text-align: center;
    color: #ff00ff;
    font-size: 12px;
    padding: 24px;
    border-top: 1px solid #ff00ff44;
  }
  .footer a { color: #00ffff; text-decoration: none; }
  .footer .author { color: #ffee00; margin-top: 6px; }
</style>
</head>
<body>
  <div class="header">
    <h1>TerminatorZ v3.0</h1>
    <div class="subtitle">Offensive CVE Exploitation Framework</div>
    <p><strong>Target:</strong> $domain</p>
    <p><strong>Date:</strong> $timestamp</p>
    <p><strong>Run:</strong> $run_label</p>
    <p><strong>By:</strong> Black Hat Ethical Hacking</p>
  </div>

  <h2>Executive Summary</h2>
  <table>
    <tr><th>Metric</th><th>Count</th></tr>
    <tr><td>Total URLs scanned</td><td>$TOTAL_URLS</td></tr>
    <tr><td class="count-critical">Critical</td><td class="count-critical">$VULN_CRITICAL</td></tr>
    <tr><td class="count-high">High</td><td class="count-high">$VULN_HIGH</td></tr>
    <tr><td class="count-medium">Medium</td><td class="count-medium">$VULN_MEDIUM</td></tr>
    <tr><td class="count-low">Low</td><td class="count-low">$VULN_LOW</td></tr>
  </table>

  <h2>Findings</h2>

  <h3 class="critical">Critical</h3>
  $critical_html

  <h3 class="high">High</h3>
  $high_html

  <h3 class="medium">Medium</h3>
  $medium_html

  <h3 class="low">Low</h3>
  $low_html

  <div class="footer">
    <p>This report was generated for authorised security testing only.</p>
    <p><strong>Generated by TerminatorZ v3.0</strong></p>
    <p><a href="https://www.blackhatethicalhacking.com">www.blackhatethicalhacking.com</a></p>
    <p class="author">Author: Chris 'SaintDruG' Abou-Chabké</p>
  </div>
</body>
</html>
HTMLEOF
}

# Produce one .finding block per parsed line at the requested severity
_findings_html_blocks() {
    local findings_file=$1
    local sev=$2
    if [ ! -f "$findings_file" ]; then
        echo '<div class="none">None.</div>'
        return
    fi

    local any=0
    local out=""
    local sev_lower
    sev_lower=$(echo "$sev" | tr '[:upper:]' '[:lower:]')

    while IFS='|' read -r s name tgt poc prf; do
        [ "$s" != "$sev" ] && continue
        any=1
        local name_e tgt_e poc_e prf_e
        name_e=$(_html_escape "$name")
        tgt_e=$(_html_escape  "$tgt")
        poc_e=$(_html_escape  "$poc")
        prf_e=$(_html_escape  "$prf")
        out+="<div class=\"finding ${sev_lower}\">"
        out+="<div class=\"finding-name\">${name_e}</div>"
        out+="<div class=\"finding-row\"><span class=\"label\">Target:</span> <span class=\"value\">${tgt_e}</span></div>"
        out+="<div class=\"finding-row\"><span class=\"label\">PoC:</span> <span class=\"value\">${poc_e}</span></div>"
        if [ -n "$prf" ]; then
            out+="<div class=\"finding-row\"><span class=\"label\">Proof:</span> <span class=\"value proof\">${prf_e}</span></div>"
        fi
        out+="</div>"
    done < <(_parse_findings "$findings_file")

    if [ $any -eq 0 ]; then
        echo '<div class="none">None.</div>'
    else
        echo "$out"
    fi
}

_html_escape() {
    local s=$1
    s=${s//&/&amp;}
    s=${s//</&lt;}
    s=${s//>/&gt;}
    s=${s//\"/&quot;}
    printf '%s' "$s"
}

export -f generate_report generate_markdown_report generate_html_report
export -f _parse_findings _findings_html_blocks _html_escape
